=== AndrewWPhillips/HexEdit/HexEdit/TestData/BinaryFileFormat.dtd
<!ELEMENT binary_file_format ((define_struct)*, (struct|use_struct|for|if|switch|jump|eval|data)*) >
<!ELEMENT define_struct (struct|use_struct|for|if|switch|jump|eval|data)* >
<!ELEMENT struct (struct|use_struct|for|if|switch|jump|eval|data)* >
<!ELEMENT use_struct EMPTY>
<!ELEMENT for (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT if ((struct|use_struct|for|if|switch|jump|data), (else, (struct|use_struct|for|if|switch|jump|data))? ) >
<!ELEMENT else EMPTY>
<!ELEMENT switch (case)* >
<!ELEMENT case (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT jump (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT eval EMPTY>
<!ELEMENT data EMPTY>
<!ATTLIST binary_file_format name CDATA #IMPLIED
              web_site CDATA #IMPLIED
              default_byte_order (big|little) "little"
              default_read_only (false|true) "false"
              default_char_set (ascii|ansi|oem|ebcdic) "ansi"
              expr CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST define_struct
              expr CDATA #IMPLIED
              type_name CDATA #REQUIRED
              pack CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST struct name CDATA #IMPLIED
              expr CDATA #IMPLIED
              type_name CDATA #IMPLIED
              pack CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST use_struct name CDATA #IMPLIED
              expr CDATA #IMPLIED
              type_name CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST for name CDATA #IMPLIED
              count CDATA #IMPLIED
              stop_test CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST if
              test CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST switch
              test CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST case
              range CDATA #REQUIRED>
<!ATTLIST jump
              offset CDATA #REQUIRED
              origin (start|current|end) "current"
              comment CDATA #IMPLIED>
<!ATTLIST eval
              expr CDATA #REQUIRED
              display_error (false|true) "false"
              display_result (false|true) "false"
              comment CDATA #IMPLIED>
<!ATTLIST data name CDATA #IMPLIED
              type CDATA #REQUIRED
              format CDATA #IMPLIED
              len CDATA #IMPLIED
              bits CDATA #IMPLIED
              direction (up|down) "up"
              straddle (false|true) "false"
              byte_order (default|big|little) "default"
              read_only (default|false|true) "default"
              domain CDATA #IMPLIED
              hide CDATA #IMPLIED
              display CDATA #IMPLIED
              units CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_HEM.xml
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="HexEdit_Macro_File" type_name="" comment="">
	<struct name="header" type_name="" comment=""><data type="int" name="magic" format="unsigned" len="2" domain="this == 0xCDAB" display="hex" comment="&quot;magic&quot; number that always has this value for HexEdit macro files"/><data type="int" name="header_len" format="unsigned" len="2" display="" comment="Length of header (not including the previous field and this length field)"/><data type="int" name="plays" format="unsigned" len="4" display="" comment="Number of times the macro is played if called from another macro."/><data type="none" name="unused" len="20"/><data type="int" name="halt_level" format="signed" len="2" display="" comment="Determines the level of erro-condition that will stop the macro" domain="{ WARNINGS, MINOR, MAJOR }"/><data type="string" name="comment" format="ascii" display="" comment="Describes the macro -- shown when the macro file is loaded."/><data type="int" name="marker" format="unsigned" len="1" domain="this == 0xCD &amp;&amp; addressof(this) == (header_len+3)" display="hex" comment="Last byte of the header (always contains 0xCD)."/></struct><for name="key" count="" stop_test="" type_name="" comment=""><struct name="" type_name="" comment=""><data type="int" name="key_id" format="unsigned" len="1" display="" domain="{ new=1, open, print_setup, exit, find_text, toolbar, replace_text, bar, prop, prop_file, prop_char, prop_dec, prop_float, prop_ibmfp, prop_checksum, prop_close, calc_dlg, calc_close, help, topics, tips, about, focus, mainsys, childsys, encrypt_alg, encrypt_password, prop_date, prop_crc, prop_stats, prop_digest, macro_message, macro_play, bookmarks_goto, calc=50, user, clear, clear_entry, equals, change_bits, change_base, endian, binop, unaryop, memget, memstore, memclear, memadd, memsubtract, close=101, save, saveas, print, preview, undo, redo, cut, copy, paste, del, copy_hex, copy_decimal, copy_binary, copy_cchar, copy_cstring, copy_cword, copy_cdword, copy_cqword, copy_cfloat, copy_cdouble, paste_ascii, paste_unicode, paste_ebcdic, sel_all, write_file, append_file, read_file, find_dlg, find_close, find_back, find_forw, find_sel, goto, ro_rw, ovr_ins, mark_pos, goto_mark, extendto_mark, swap_mark, highlight, aerial, autofit, font, inc_font, dec_font, addr, char_area, ebcdic, control, control2, graphic, oem, rowsize, group_by, offset, win_new, win_next, win_cmd, redraw, scroll_up, scroll_down, swap_areas, start_line, key, char, mouse, shift_mouse, hscroll, vscroll, address_tool, compare, inc8, inc16, inc32, inc64, dec8, dec16, dec32, dec64, flip16, flip32, flip64, u1, u2, go, markstore, markclear, markadd, marksubtract, markatstore, selstore, selatstore, selendstore, sellenstore, markget, markat, bookmark, bookmarkat, selget, selat, selend, sellen, eofget, invert, neg8, neg16, neg32, neg64, sel_line, convert, encrypt, append_same_file, undo_changes, hex_area, display_reset, area, charset, scheme, display_state, import_motorola, import_intel, import_text, op_binary, op_unary, checksum, address_hex, address_dec, bookmarks, bookmarks_add, find_next, bookmark_all, replace, replace_all, dffd_sync }"/><if test="!(key_id == 167 || key_id == 168 || key_id == 2 || key_id == 5 || key_id == 7 || key_id == 23 || key_id == 26 || key_id == 27 || key_id == 32 || key_id == 33 || key_id == 34 || key_id == 128 || key_id == 219 || key_id == 221 || key_id == 222 || key_id == 223 || key_id == 227 || key_id == 228 || key_id == 230)" comment=""><data type="int" name="data" format="signed" len="8" display=""/></if><if test="key_id == 2 || key_id == 5 || key_id == 7 || key_id == 23 || key_id == 26 || key_id == 27 || key_id == 32 || key_id == 33 || key_id == 34 || key_id == 128 || key_id == 219 || key_id == 221 || key_id == 222 || key_id == 223 || key_id == 227 || key_id == 228 || key_id == 230" comment=""><struct name="string" type_name="" comment=""><data type="int" name="length" format="unsigned" len="2" display=""/><data type="string" name="str" format="ascii" display="" len="length"/><data type="char" name="EOS" format="ascii" domain="this == 0" display=""/></struct></if><if test="key_id == 167 || key_id == 168" comment=""><struct name="mouse_sel" type_name="" comment=""><data type="int" name="X" format="signed" len="4" display=""/><data type="int" name="Y" format="signed" len="4" display=""/><data type="int" name="unused" format="signed" len="4" display=""/><data type="int" name="CY" format="signed" len="8" display=""/><data type="none" name="pad" len="4"/></struct></if><if test="key_id == 144" comment=""><struct name="font" type_name="" comment=""><data type="int" name="height" format="unsigned" len="4" display="" comment="Font height" type_name="lfHeight"/><data type="int" name="charset" format="unsigned" len="1" display="" type_name="lfCharSet"/><data type="int" name="strlen" format="unsigned" len="2" display=""/><data type="string" name="name" format="ascii" display="" len="length" type_name="lfFaceName"/><data type="char" name="EOS" format="ascii" domain="this == 0" display=""/></struct></if></struct></for></binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_IFF.XML
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="IFF" type_name="" comment="The venerable interchange file format invented by EA and Commodore for Amiga.  Can be used to contain any sort of data chunks and there are standard definitions for many types such as pictures (ILBM), sound (8SVX), video (ANIM) etc. Usually has the file extension .IFF but sometimes .LBM when it contains a picture (ILBM chunk)." default_byte_order="big" default_read_only="false" default_char_set="ascii" web_site="http://www.szonye.com/bradd/iff.html" expr="">
	<define_struct type_name="CHUNK" comment="Everything in IFF is a chunk and/or part of a chunk." expr="this.CKID">
		<data type="string" name="CKID" format="default" len="4" display="" type_name="ckID" comment="Identifies the type ot the following chunk.  This is 4 ASCII characters (or 32-bit number)."/>
		<data type="int" name="LENGTH" format="unsigned" len="4" display="" units="bytes" comment="Length of the chunk excluding the CKID and LENGTH fields." type_name="ckSize"/>
		<switch test="CKID" comment="The rest of the chunk is interpreted differently based on the chunk ID (CKID).  We handle the IFF admin chunks here (FORM, CAT , LIST, PROP) and some standard ones we understand.  We can add to this list as info is obtained on other standard chunk types.  The last (UNKNOWN) entry in the list just skips any chunks we know nothing about. ">
			<case range="FORM">
				<struct name="FORM" type_name="" comment="The only thing in a FORM chunk apart from the nested chunks is this ID.  It provides a name space for the nested chunks to eliminate chunk ID conflicts." expr="this.FORMTYPE">
					<data type="string" name="FORMTYPE" format="default" len="4" display=""/>
					<for name="LOCALCHUNK" count="" stop_test="addressof(this)+sizeof(this) &gt;= addressof(FORMTYPE) + LENGTH" type_name="" comment="Zero or more nested chunks.">
						<use_struct name="" expr="" type_name="CHUNK" comment=""/>
					</for>
				</struct>
			</case>
			<case range="CAT ">
				<struct name="CAT" type_name="" comment="Typically used to store a concatenation of FORM chunks of the same type.  Note the trailing space in the chunk ID &quot;CAT &quot;." expr="">
					<data type="string" name="CONTENTSTYPE" format="default" len="4" display="" comment="Type of FORMs stored in the CAT or blank if there are different types."/>
					<for name="NESTEDCHUNK" count="" stop_test="addressof(this)+sizeof(this) &gt;= addressof(CONTENTSTYPE) + LENGTH" type_name="" comment="">
						<use_struct name="" expr="" type_name="CHUNK" comment=""/>
					</for>
				</struct>
			</case>
			<case range="LIST">
				<struct name="LIST" type_name="" comment="Allows grouping of chunk with shared properties.  NOTE: The template does not verify that the nested PROP chunks all occur before the other nested chunks" expr="">
					<data type="string" name="CONTENTSTYPE" format="default" len="4" display=""/>
					<for name="NESTEDCHUNK" count="" stop_test="addressof(this)+sizeof(this) &gt;= addressof(CONTENTSTYPE) + LENGTH" type_name="" comment="">
						<use_struct name="" expr="" type_name="CHUNK" comment=""/>
					</for>
				</struct>
			</case>
			<case range="PROP">
				<struct name="PROP" type_name="" comment="" expr="">
					<data type="string" name="FORMTYPE" format="default" len="4" display=""/>
					<for name="PROP" count="" stop_test="addressof(this)+sizeof(this) &gt;= addressof(FORMTYPE) + LENGTH" type_name="" comment="">
						<use_struct name="" expr="" type_name="CHUNK" comment=""/>
					</for>
				</struct>
			</case>
			<case range="BMHD">
				<struct name="BMHD" type_name="" comment="" expr="">
					<data type="int" name="width" format="unsigned" len="2" display="" units="pixels" type_name="UWORD" comment="raster width"/>
					<data type="int" name="height" format="unsigned" len="2" display="" units="pixels" type_name="UWORD" comment="raster height"/>
					<data type="int" name="x" format="signed" len="2" display="" units="pixel" type_name="WORD" comment="x position"/>
					<data type="int" name="y" format="signed" len="2" display="" units="pixels" type_name="WORD" comment="y position"/><data type="int" name="nPlanes" format="unsigned" len="1" display="" type_name="UBYTE" comment="Number of bitplanes.  Should be no more than 8?"/>
					<data type="int" name="masking" format="unsigned" len="1" display="" type_name="Masking" domain="{None, HasMask, HasTransparentColor, Lasso}"/>
					<data type="int" name="compression" format="unsigned" len="1" display="" type_name="Compression" domain="{None, ByteRun1}"/>
					<data type="int" name="pad1" format="unsigned" len="1" display="" type_name="UBYTE" domain="this == 0"/>
					<data type="int" name="transparentColor" format="unsigned" len="2" display="" type_name="UWORD"/>
					<data type="int" name="xAspect" format="unsigned" len="1" display="" type_name="UBYTE"/>
					<data type="int" name="yAspect" format="unsigned" len="1" display="" type_name="UBYTE"/>
					<data type="int" name="pageWidth" format="signed" len="2" display="" units="pixels" type_name="WORD"/>
					<data type="int" name="pageHeight" format="signed" len="2" display="" units="pixels" type_name="WORD"/>
				</struct>
			</case>
			<case range="CMAP">
				<struct name="CMAP" type_name="ColorRegister" comment="" expr="">
					<for name="Color" count="LENGTH/3" stop_test="" type_name="" comment="">
						<struct name="RGB" type_name="ColorRegister" comment="" expr="">
							<data type="int" name="red" format="unsigned" len="1" display="" type_name="UBYTE"/>
							<data type="int" name="green" format="unsigned" len="1" display="" type_name="UBYTE"/>
							<data type="int" name="blue" format="unsigned" len="1" display="" type_name="UBYTE"/>
						</struct>
					</for>
					<data type="none" name="" len="addressof(this)%2" comment="Padding to make sure CMAP is even"/></struct>
			</case>
			<case range="">
				<data type="none" name="UNKNOWN" len="LENGTH" comment="Unrecognised CHUNK ID"/>
			</case>
		</switch>
	</define_struct>
	<use_struct name="MAIN" expr="this.CKID" type_name="CHUNK" comment=""/>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_DBX.XML
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="DBX" type_name="" comment="Microsoft Outlook Express .DBX file" default_byte_order="little" default_read_only="true" default_char_set="ansi" web_site="http://oedbx.Aroh.de/" allow_editing="false">
	<struct name="file_header" type_name="" comment=""><data type="int" name="magic" format="unsigned" len="4" domain="this == 0xFE12ADCF" display="hex"/><data type="int" name="flag" format="unsigned" len="1" domain="{OFFLINE=48, MESSAGES=197, FOLDERS, POP3UIDL }" display="" comment="Seems to be the first byte of a CLSID but can be used to distinguish the different file types."/><data type="none" name="fill1" len="0x17"/><data type="int" name="file_info_size" format="unsigned" len="4" display=""/><data type="none" name="fill2" len="0x54 - 0x20"/><data type="int" name="space_used" format="unsigned" len="4" display=""/><data type="int" name="space_reuse" format="unsigned" len="4" display=""/><data type="none" name="fill3" len="0x88 - 0x5C"/><data type="int" name="ptr_message_cond" format="unsigned" len="4" display="hex"/><data type="int" name="ptr_folder_cond" format="unsigned" len="4" display="hex"/><data type="none" name="fill4" len="0x27C - 0x90"/><data type="int" name="space_indexed" format="unsigned" len="4" display="" comment="used space for indexed info objects"/><data type="int" name="used_conditions" format="unsigned" len="4" display="" comment="used space for conditions objects"/><data type="none" name="fill5" len="4"/><data type="int" name="used_folder" format="unsigned" len="4" display="" comment="used space for folder list objects"/><data type="int" name="used_tree" format="unsigned" len="4" display="" comment="used space for tree objects"/><data type="int" name="used_message" format="unsigned" len="4" display="" comment="used space for message objects"/><for name="deleted_object" count="2048" stop_test="" type_name="" comment="Each int4 value points to a single linked list of deleted objects from the variable segments. The objects in each list have the same size : address of the pointer - 0x29c"><data type="int" name="" format="unsigned" len="4" display=""/></for><data type="none" name="fill6" len="0x24BC - 0x2294"/></struct><if test="file_header.flag == 197" comment=""><struct name="message_file_info" type_name="" comment=""><data type="int" name="fill1" format="signed" len="4" display=""/><data type="int" name="type" format="unsigned" len="1" domain="{News, LocalStore=3}" display=""/><data type="string" name="reg_key" format="ascii" len="256" display=""/><data type="string" name="folder_name" format="ascii" len="256" display=""/><data type="none" name="fill2" len="addressof(message_file_info) + file_header.file_info_size - addressof(folder_name) - sizeof(folder_name)" comment="Just fills to size of file_info_size"/></struct></if><if test="file_header.flag == 198" comment=""><struct name="folders_file_info" type_name="" comment=""><data type="date" name="created" format="filetime" display=""/><data type="none" name="fill" len="256"/></struct></if><for name="segment" count="2" stop_test="" type_name="" comment=""><struct name="" type_name="" comment=""><data type="int" name="marker" format="unsigned" len="4" display="hex"/><if test="addressof(marker) == file_header.ptr_folder_cond || addressof(marker) == file_header.ptr_message_cond" comment=""><struct name="conditions" type_name="" comment=""><data type="int" name="len" format="unsigned" len="4" display=""/><data type="string" name="cond_str" format="ascii" len="len" display=""/></struct></if></struct></for><data type="none" name="none"/>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/Install/Templates/_ico.xml
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="Windows_icon" allow_editing="false" comment="File format for Windows icons">
    <define_struct type_name="BITMAPICONIMAGE" comment="Contains an icon image in bitmap format">
        <eval expr="bitmapOffset = addressof(this)" display_error="false" display_result="false"/>
        <struct name="header" type_name="BITMAPINFOHEADER" comment="DIB header">
            <data name="headerSize" type="int" len="4" format="signed" units="bytes" comment="Size of this structure" domain="this &gt;= 40"/>
            <data name="width" type="int" len="4" format="signed" units="pixels" domain="this &gt; 0"/>
            <data name="height" type="int" len="4" format="signed" units="pixels" domain="this &gt; 0" comment="Specifies the combined height of the XOR and AND masks"/>
            <data name="planes" type="int" len="2" format="signed" domain="this == 1" comment="These files always seem to contain just one plane."/>
            <data name="bitCount" type="int" len="2" domain="this==1||this==4||this==8||this==16||this==24||this==32" format="signed" comment="Bits per pixel. If 8 or less each pixel is an index into the palette.  If 16 or more the pixel itself contains the colour info." units="bits / pixel"/>
            <data name="compression" type="int" len="4" format="signed" comment="Not used."/>
            <data name="imageSize" type="int" len="4" format="signed" comment="Size of the bitmap itslef  - may be zero if compression is zero (off)." units="bytes"/>
            <data name="xPelsPerMeter" type="int" len="4" format="signed" units="pixels / meter" comment="Not used."/>
            <data name="yPelsPerMeter" type="int" len="4" format="signed" units="pixels / meter" comment="Not used."/>
            <data name="clrUsed" type="int" len="4" format="signed" comment="Not used."/>
            <data name="clrImportant" type="int" len="4" format="signed" comment="Not used."/>
        </struct>
        <if test="header.bitCount &lt; 16" comment="Colour lookup table.  This is not needed if the pixel values are actual colours and not indices into the palette.">
            <for name="colour" count="1 &lt;&lt; header.bitCount" stop_test="" type_name="" comment="Array of colours">
              <struct type_name="RGBQUAD" name="" comment="One colour - entry in the palette">
                  <data name="blue" type="int" format="unsigned" len="1"/>
                  <data name="green" type="int" format="unsigned" len="1"/>
                  <data name="red" type="int" format="unsigned" len="1"/>
                  <data name="resvd" type="int" format="unsigned" len="1" domain="this == 0" comment="Not currently used"/>
              </struct>
            </for>
        </if>
        <eval expr="xorSize = ((((header.bitCount*header.width)+31)/32)*4)*(header.height/2)" display_error="false" display_result="false"/>
        <eval expr="andSize = (((header.width+31)/32)*4)*(header.height/2)" display_error="false" display_result="false"/>
        <if test="header.imageSize == 0 || header.imageSize == (xorSize + andSize)">
            <struct name="pixelData" comment="Pixel data (XOR and AND mask)">
                <data name="xor" type="none" len="xorSize" comment="DIB bits for XOR mask"/>
                <data name="and" type="none" len="andSize" comment="DIB bits for monochrome AND mask"/>
            </struct>
        <else/>
            <data name="pixelData" type="none" len="imageBytes - (addressof(this) - bitmapOffset)" comment="Pixel data (possibly compressed)"/>
        </if>
    </define_struct>
    <eval expr="totalDataSize = 0" display_error="false" display_result="false"/>
    <eval expr="imageBytes = 0" display_error="false" display_result="false"/>
    <data name="reserved" type="int" format="unsigned" len="2" comment="Should always be 0"/>
    <data name="type" type="int" format="unsigned" len="2" domain="{ICON=1,CURSOR=2}" comment="1 for icon (.ICO), 2 for cursor (.CUR) file"/>
    <data name="count" type="int" format="unsigned" len="2" comment="Number of images in the file"/>
    <for name="icon" count="count" stop_test="" type_name="" comment="Stores general information about every image in the file.">
      <struct type_name="ICONDIRENTRY" comment="" expr="">
          <data name="width" type="int" format="unsigned" len="1"/>
          <data name="height" type="int" format="unsigned" len="1"/>
          <data name="colourCount" type="int" format="unsigned" len="1" comment="Number of colors in image (0 if &gt;=8bpp)"/>
          <data name="reserved" type="int" format="unsigned" len="1" comment="Should always be 0"/>
          <data name="planes" type="int" format="unsigned" len="2" comment="Colour planes"/>
          <data name="bitCount" type="int" format="unsigned" len="2" comment="Bits per pixel"/>
          <data name="bytesInRes" type="int" format="unsigned" len="4" comment="How many bytes in this resource?"/>
          <eval expr="imageBytes = bytesInRes" display_error="false" display_result="false"/>
          <eval expr="totalDataSize = totalDataSize + bytesInRes" display_error="false" display_result="false"/>
          <data name="imageOffset" type="int" format="unsigned" len="4" display="hex" comment="Where in the file is this image?"/>
          <jump offset="imageOffset" comment="" origin="start">
              <use_struct name="bitmapImage" expr="" type_name="BITMAPICONIMAGE" comment=""/>
          </jump>
      </struct>
    </for>
    <data name="" type="none" len="totalDataSize" comment="Skip past icon images already read in the jump"/>
</binary_file_format>
