=== AndrewWPhillips/HexEdit/HexEdit/TestData/BinaryFileFormat.dtd
<!ELEMENT binary_file_format ((define_struct)*, (struct|use_struct|for|if|switch|jump|eval|data)*) >
<!ELEMENT define_struct (struct|use_struct|for|if|switch|jump|eval|data)* >
<!ELEMENT struct (struct|use_struct|for|if|switch|jump|eval|data)* >
<!ELEMENT use_struct EMPTY>
<!ELEMENT for (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT if ((struct|use_struct|for|if|switch|jump|data), (else, (struct|use_struct|for|if|switch|jump|data))? ) >
<!ELEMENT else EMPTY>
<!ELEMENT switch (case)* >
<!ELEMENT case (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT jump (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT eval EMPTY>
<!ELEMENT data EMPTY>
<!ATTLIST binary_file_format name CDATA #IMPLIED
              web_site CDATA #IMPLIED
              default_byte_order (big|little) "little"
              default_read_only (false|true) "false"
              default_char_set (ascii|ansi|oem|ebcdic) "ansi"
              expr CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST define_struct
              expr CDATA #IMPLIED
              type_name CDATA #REQUIRED
              pack CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST struct name CDATA #IMPLIED
              expr CDATA #IMPLIED
              type_name CDATA #IMPLIED
              pack CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST use_struct name CDATA #IMPLIED
              expr CDATA #IMPLIED
              type_name CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST for name CDATA #IMPLIED
              count CDATA #IMPLIED
              stop_test CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST if
              test CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST switch
              test CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST case
              range CDATA #REQUIRED>
<!ATTLIST jump
              offset CDATA #REQUIRED
              origin (start|current|end) "current"
              comment CDATA #IMPLIED>
<!ATTLIST eval
              expr CDATA #REQUIRED
              display_error (false|true) "false"
              display_result (false|true) "false"
              comment CDATA #IMPLIED>
<!ATTLIST data name CDATA #IMPLIED
              type CDATA #REQUIRED
              format CDATA #IMPLIED
              len CDATA #IMPLIED
              bits CDATA #IMPLIED
              direction (up|down) "up"
              straddle (false|true) "false"
              byte_order (default|big|little) "default"
              read_only (default|false|true) "default"
              domain CDATA #IMPLIED
              hide CDATA #IMPLIED
              display CDATA #IMPLIED
              units CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_TGA.XML
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">

<binary_file_format name="TARGA_format" 
   type_name="" comment="" default_byte_order="little" 
   default_read_only="false" default_char_set="ascii" 
   web_site="http://www.dca.fee.unicamp.br/~martino/disciplinas/ea978/tgaffs.pdf"
   allow_editing="false">
  <struct name="TARGA_header" type_name="" comment="">
    <data type="int" name="idlen" format="unsigned" len="1" display="dec"
comment="ID Length"/>
    <data type="int" name="cmap_type" format="unsigned" len="1" display="dec"
 comment="CMAP Type: 0 or 1 "/>
    <data type="int" name="image_type" format="unsigned" len="1"  display="dec"
 comment="Image Type"/>
    <data type="int" name="FEI" format="unsigned" len="2" display="dec"
comment="First entry index"/>
    <data type="int" name="CML" format="unsigned" len="2" display="dec"
comment="Color Map Length"/>
    <data type="int" name="CMES" format="unsigned" len="1" display="dec"
comment="Color Map entry Size"/>
    <data type="int" name="xorigin" format="unsigned" len="2" display="dec"/>
    <data type="int" name="yorigin" format="unsigned" len="2" display="dec"/>
    <data type="int" name="width" format="unsigned" len="2" display="dec"/>
    <data type="int" name="height" format="unsigned" len="2" display="dec"/>
    <data type="int" name="pixel_depth" format="unsigned" len="1"
display="dec"/>
    <data type="int" name="image_descriptor" format="unsigned" len="1"
display="dec"/>
    <if test="idlen !=0x00 0" comment="">
      <data type="string" name="iddescription" format="ascii" len="idlen"
 display=""/>
    </if>
  </struct>

  <if test="TARGA_header.cmap_type != 0x00" comment="">
    <struct name="cmap_data" type_name="" comment="">
      <for name="empty" count="" stop_test="this.marker == TARGA_header.FEI"
      type_name="" comment="">
        <data type="int" name="empty" format="unsigned" len="1" display="dec"/>
      </for>
      <for name="color" count="" stop_test="this.marker ==
TARGA_header.FEI+TARGA_header.CML" type_name="" comment="">
        <data type="int" name="image_descriptor" format="unsigned"
      len="TARGA_header.CMES" display="hex"/>
      </for>
    </struct>
  </if>
  <if test="TARGA_header.image_type != 0x00" comment="">
    <struct name="image_data" type_name="" comment="">
      <for name="pixel" count="" stop_test="this.marker ==
TARGA_header.width*TARGA_header.height" type_name="" comment="">
        <data type="int" name="pixel" format="unsigned"
    len="TARGA_header.pixel_depth/8" display="hex"/>
      </for>
    </struct>
  </if>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/HEG.xml
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="HEG_File" type_name="" comment="" expr="{rect_count} rectangles, {circle_count} circles">
	<define_struct type_name="object" comment="" expr="{this.type==1?&quot;RECT&quot;:(this.type==2?&quot;CIRCLE&quot;:(this.type==10?&quot;GROUP&quot;:&quot;END&quot;))}">
		<data type="int" name="type" format="signed" len="1" domain="{END=0, RECT, CIRCLE, GROUP=10}"/>
		<data type="int" name="flags" format="unsigned" len="1" display="hex" domain="this == 0"/>
		<if test="type == 1">
			<struct name="rect" type_name="" comment="" expr="{this.width} X {this.height}">
				<data type="int" name="colid" format="unsigned" len="2"/>
				<data type="real" name="x" format="ieee" len="4"/>
				<data type="real" name="y" format="ieee" len="4"/>
				<data type="real" name="width" format="ieee" len="4" domain="this &gt; 0.0"/>
				<data type="real" name="height" format="ieee" len="4" domain="this &gt; 0.0"/>
				<eval expr="rect_count = rect_count + 1" display_error="false" display_result="false" comment=""/></struct>
		</if>
		<if test="type == 2">
			<struct name="circle" type_name="" comment="">
				<data type="int" name="colid" format="unsigned" len="2"/>
				<data type="real" name="x" format="ieee" len="4"/>
				<data type="real" name="y" format="ieee" len="4"/>
				<data type="real" name="radius" format="ieee" len="4" domain="this &gt; 0.0"/>
				<eval expr="circle_count = circle_count + 1" display_error="false" display_result="false" comment=""/></struct>
		</if>
		<if test="type == 10">
			<struct name="group">
				<data type="int" name="count" format="unsigned" len="2" comment="Number of grouped objects." domain="this &gt; 0"/>
				<data type="real" name="x" format="ieee" len="4"/>
				<data type="real" name="y" format="ieee" len="4"/>
				<for name="sub_object" count="count">
					<use_struct type_name="object"/>
				</for>
			</struct>
		</if>
		<eval expr="rect_count" display_error="false" display_result="false" comment=""/>
	</define_struct>
	<struct name="header">
		<data type="int" name="magic" format="unsigned" len="4" domain="this == 0x16071958" display="hex" comment="HEG file magic number - should always be 16071958 hex."/>
		<data type="date" name="created" format="c" comment="When the image was created." display="%c"/>
		<data type="date" name="modified" format="c" comment="When the image was last changed." domain="this &gt; created"/>
		<data type="int" name="colour_table_address" format="unsigned" len="4" display="hex" comment="Address in the file of the colours table."/>
	</struct>
	<eval expr="rect_count = circle_count = 0" display_error="false" display_result="false" comment=""/>
	<for name="object" stop_test="this.type ==0" count="" type_name="" comment="">
		<use_struct type_name="object"/>
	</for>
	<struct name="col_table">
		<data type="int" name="num_cols" format="unsigned" len="2" domain="this &gt; 0"/>
		<for name="col" count="num_cols">
			<struct>
				<data type="string" name="name" format="ascii" len="13"/>
				<data type="int" name="red" format="unsigned" len="1"/>
				<data type="int" name="green" format="unsigned" len="1"/>
				<data type="int" name="blue" format="unsigned" len="1"/>
			</struct>
		</for>
	</struct>
	<eval expr="{rect_count} rectangles, {circle_count} circles" display_error="false" display_result="true" comment=""/>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/Install/Templates/_bmp.xml
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="Windows_bitmap" comment="File format for storing Windows device independent bitmap."
                    expr="{this.infohdr.width} X {this.infohdr.height} @ {this.infohdr.bitcount} bpp" allow_editing="false">
	<struct name="filehdr" type_name="BITMAPFILEHEADER" comment="Info related to the file" expr="">
		<data name="type" type="string" len="2" domain="this==&quot;BM&quot;" format="ascii" display="" comment="Magic number"/>
		<data name="size" type="int" len="4" format="signed" display="" comment="Size of the whole file." units="bytes"/>
		<data name="reserved1" type="int" len="2" domain="this==0" format="signed" display=""/>
		<data name="reserved2" type="int" len="2" domain="this==0" format="signed" display=""/>
		<data name="offbits" type="int" len="4" format="signed" display="" comment="Offset from start of file to the bitmap data." units="bytes"/>
	</struct>
	<struct name="infohdr" type_name="BITMAPINFOHEADER" comment="Info related to the bitmap" expr="">
		<data name="size" type="int" len="4" format="signed" display="" units="bytes" comment="Size of this (BITMAPINFOHEADER) structure" domain="this &gt;= 40"/>
		<data name="width" type="int" len="4" format="signed" display="" units="pixels" domain="this &gt; 0"/>
		<data name="height" type="int" len="4" format="signed" display="" units="pixels" domain="this &gt; 0"/>
		<data name="planes" type="int" len="2" format="signed" display="" domain="this == 1" comment="These files always seem to contain just one plane."/>
		<data name="bitcount" type="int" len="2" domain="this==1||this==4||this==8||this==16||this==24||this==32" format="signed" display=""
              comment="Bits per pixel.  If 8 or less each pixel is an index into the palette.  If 16 or more the pixel itself contains the colour info."
              units="bits / pixel"/>
		<data name="compression" type="int" len="4" format="signed" display="" comment="Usually zero (no compression)." domain="{NONE, RLE8BIT, RLE4BIT, RGB_MASK}"/>
		<data name="sizeimage" type="int" len="4" format="signed" display="" comment="Size of the bitmap itslef  - may be zero if compression is zero (off)." units="bytes"/>
		<data name="xpelspermeter" type="int" len="4" format="signed" display="" units="pixels / meter" comment="Horizontal size in the real world - often zero."/>
		<data name="ypelspermeter" type="int" len="4" format="signed" display="" units="pixels / meter" comment="Vertical size in the real world - often zero."/>
		<data name="clrused" type="int" len="4" format="signed" display=""
              comment="Number of colour in the palette that are used - can be zero if not specified." domain="this &lt;= 256"/>
		<data name="clrimportant" type="int" len="4" format="signed" display="" comment="Number of *important* colours in the palette - can be zero if not specified."/>
	</struct>
	<if test="infohdr.size &gt; sizeof(infohdr)" comment="Optional info - not sure what this is for but never appears to be used">
		<data name="extra" type="none" len="infohdr.size - sizeof(infohdr)"/>
	</if>
	<if test="infohdr.bitcount &lt; 16" comment="Colour lookup table.  This is not needed if the pixel values are actual colours and not indices into the palette.">
		<for name="colour" count="1 &lt;&lt; infohdr.bitcount" stop_test="" type_name="" comment="Array of colours">
			<struct type_name="RGBQUAD" name="" comment="One colour - entry in the palette" expr="">
				<data name="blue" type="int" format="unsigned" len="1" display=""/>
				<data name="green" type="int" format="unsigned" len="1" display=""/>
				<data name="red" type="int" format="unsigned" len="1" display=""/>
				<data name="resvd" type="int" format="unsigned" len="1" domain="this == 0" display="" comment="Not currently used"/>
			</struct>
		</for>
	</if>
	<data name="bitmap" type="none" len="filehdr.size - addressof(this)" comment="This is the actual pixel data."/>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_JPG.XML
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="JPEG_file_interchange_format" type_name="" comment="" default_byte_order="big" default_read_only="false" default_char_set="ascii" web_site="http://www.w3.org/Graphics/JPEG/">
	<data type="int" name="SOI" format="unsigned" len="2" domain="this == 0xFFD8" display="hex" comment="Start of information marker"/><struct name="APP0_segment" type_name="" comment=""><data type="int" name="marker" format="unsigned" len="2" domain="this == 0xFFE0" display="hex" comment="APP0 marker"/><data type="int" name="length" format="unsigned" len="2" display=""/><data type="string" name="identifier" format="ascii" len="5" domain="this == &quot;JFIF&quot;" display=""/><data type="int" name="version" format="unsigned" len="2" display="hex"/><data type="int" name="units" format="unsigned" len="1" domain="{ NONE, DPI, DPcm }" display=""/><data type="int" name="Xdensity" format="unsigned" len="2" display=""/><data type="int" name="Ydensity" format="unsigned" len="2" display=""/><data type="int" name="Xthumbnail" format="unsigned" len="1" display=""/><data type="int" name="Ythumbnail" format="unsigned" len="1" display=""/><data type="none" name="RGBn" len="3 * Xthumbnail * Ythumbnail"/></struct><for name="segment" count="" stop_test="this.marker == 0xFFD9" type_name="" comment=""><struct name="" type_name="" comment=""><data type="int" name="marker" format="unsigned" len="2" display="hex" domain="this &gt;= 0xFFC0" comment="This value determines what type of segment follows."/><if test="marker != 0xFFDA &amp;&amp; marker !=0xFFD9" comment=""><struct name="Other" type_name="" comment="Other data segments apart from SOS"><data type="int" name="length" format="unsigned" len="2" display="" comment="length of the segment (not including marker but including length itself)."/><data type="none" name="rest" len="length - 2"/></struct></if><if test="marker == 0xFFDA" comment=""><struct name="SOS" type_name="" comment="Start of scan.  This is the last segment which continues to end of file except for the EOI marker (FFD9) which is included here for simplicity."><data type="int" name="length" format="unsigned" len="2" display="" comment="Scan header length.  Does not include the data length."/><data type="none" name="scan_header" len="length - 2"/><data type="none" name="data" comment="The actual image data.  Continues to EOF (except for terminating EOI marker)."/></struct></if></struct></for></binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_standard_types.xml
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="StandardTypes" comment="C/C++ standard types as used in MS compiler (VS6). This file is used in parsing C/C++ source code for declarations.">
	<data type="none"  name="void" len="0" comment='INTERNAL USE ONLY (used during parsing of "void *")'/>
	<data type="char"  name="char" format="ascii"/>
	<data type="char"  name="wchar_t" format="unicode" type_name="wchar_t"/>
	<data type="int"   name="bool" len="1" type_name="bool"/>
	<data type="int"   name="pointer$"          format="unsigned" len="4" display="hex" type_name="pointer"/>
	<data type="int"   name="function_pointer$" format="unsigned" len="4" display="hex" type_name="function pointer"/>
	<data type="int"   name="bit_field$"        direction="up"    len="4" display="bin" type_name="bit-field"/>
	<data type="int"   name="enum$"             format="signed"   len="4" type_name="enum"/>
	<data type="int"   name="short"             format="signed"   len="2" type_name="short"/>
	<data type="int"   name="int"               format="signed"   len="4" type_name="int"/>
	<data type="int"   name="long"              format="signed"   len="4" type_name="long"/>
	<data type="int"   name="signed$char"       format="signed"   len="1" type_name="signed char"/>
	<data type="int"   name="signed$short"      format="signed"   len="2" type_name="signed short"/>
	<data type="int"   name="signed$int"        format="signed"   len="4" type_name="signed int"/>
	<data type="int"   name="signed$long"       format="signed"   len="4" type_name="signed long"/>
	<data type="int"   name="unsigned$char"     format="unsigned" len="1" type_name="unsigned char"/>
	<data type="int"   name="unsigned$short"    format="unsigned" len="2" type_name="unsigned short"/>
	<data type="int"   name="unsigned$int"      format="unsigned" len="4" type_name="unsigned int"/>
	<data type="int"   name="unsigned$long"     format="unsigned" len="4" type_name="unsigned long"/>
	<data type="real"  name="float"             len="4" type_name="float"/>
	<data type="real"  name="double"            len="8" type_name="double"/>
	<data type="real"  name="long$double"       len="8" type_name="long double"/>
	<data type="date"  name="time_t"            format="c" type_name="time_t"/>
	<data type="int"   name="clock_t"           format="signed"   len="4" type_name="clock_t"/>
	<struct name="tm" type_name="struct tm" expr="date(y/m/d)={this.tm_year;%04d}/{this.tm_mon;%02d}/{this.tm_mday;%02d} time={this.tm_hour;%2d}:{this.tm_min;%02d}">
		<data type="int"   name="tm_sec"        format="signed"   len="4"/>
		<data type="int"   name="tm_min"        format="signed"   len="4"/>
		<data type="int"   name="tm_hour"       format="signed"   len="4"/>
		<data type="int"   name="tm_mday"       format="signed"   len="4"/>
		<data type="int"   name="tm_mon"        format="signed"   len="4"/>
		<data type="int"   name="tm_year"       format="signed"   len="4"/>
		<data type="int"   name="tm_wday"       format="signed"   len="4"/>
		<data type="int"   name="tm_yday"       format="signed"   len="4"/>
		<data type="int"   name="tm_isdst"      format="signed"   len="4"/>
	</struct>
	<data type="int"   name="size_t"            format="unsigned" len="4" type_name="size_t"/>
	<data type="int"   name="ptrdiff_t"         format="signed" len="4" type_name="ptrdiff_t"/>
	<data type="int"   name="sig_atomic_t"      format="signed" len="4" type_name="sig_atomic_t"/>
	<struct name="_complex" type_name="_complex" expr="({this.x}, {this.y})">
		<data type="real" name="x"             len="8"/>
		<data type="real" name="y"             len="8"/>
	</struct>
	<data type="int"   name="intptr_t"          format="unsigned" len="4" display="hex" type_name="intptr_t"/>
	<struct name="div_t" type_name="div_t" expr="quot={this.quot}, rem={this.rem}">
		<data type="int"  name="quot"           format="signed"   len="4"/>
		<data type="int"  name="rem"            format="signed"   len="4"/>
	</struct>
	<struct name="ldiv_t" type_name="ldiv_t" expr="quot={this.quot}, rem={this.rem}">
		<data type="int"  name="quot"           format="signed"   len="4"/>
		<data type="int"  name="rem"            format="signed"   len="4"/>
	</struct>
	<data type="none"  name="FILE" len="32" comment="Size could easily vary - should not be written to file"/>
	<data type="int"   name="fpos_t"            format="signed"   len="8" type_name="fpos_t"/>
	<struct name="lconv" type_name="lconv">
		<data type="int"   name="decimal_point"     format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="thousands_sep"     format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="grouping"          format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="int_curr_symbol"   format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="currency_symbol"   format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="mon_decimal_point" format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="mon_thousands_sep" format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="mon_grouping"      format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="positive_sign"     format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="negative_sign"     format="unsigned" len="4" display="hex" comment="pointer"/>
		<data type="int"   name="int_frac_digits"   format="signed"   len="1"/>
		<data type="int"   name="frac_digits"       format="signed"   len="1"/>
		<data type="int"   name="p_cs_precedes"     format="signed"   len="1"/>
		<data type="int"   name="p_sep_by_space"    format="signed"   len="1"/>
		<data type="int"   name="n_cs_precedes"     format="signed"   len="1"/>
		<data type="int"   name="n_sep_by_space"    format="signed"   len="1"/>
		<data type="int"   name="p_sign_posn"       format="signed"   len="1"/>
		<data type="int"   name="n_sign_posn"       format="signed"   len="1"/>
	</struct>
	<for name="jmp_buf" count="16" type_name="jmp_buf">
		<data type="int" len="4"/>
	</for>
	<data type="int"   name="va_list"           format="unsigned" len="4" display="hex" comment="pointer" type_name="va_list"/>
	<data type="int" name="unexpected_function" format="unsigned" len="4" display="hex" comment="func ptr" type_name="unexpected_function"/>
	<data type="int"   name="mbstate_t"         format="signed"   len="4" type_name="mbstate_t"/>
	<data type="int"   name="wctype_t"          format="unsigned" len="2" type_name="wctype_t"/>
	<data type="int"   name="wctrans_t"         format="unsigned" len="2" type_name="wctrans_t"/>
	<data type="int"   name="wint_t"            format="unsigned" len="2" type_name="wint_t"/>

	<data type="int"   name="__int8"            format="signed"   len="1" type_name="__int8"/>
	<data type="int"   name="__int16"           format="signed"   len="2" type_name="__int16"/>
	<data type="int"   name="__int32"           format="signed"   len="4" type_name="__int32"/>
	<data type="int"   name="__int64"           format="signed"   len="8" type_name="__int64"/>
	<data type="int"   name="signed$__int8"     format="signed"   len="1" type_name="signed __int8"/>
	<data type="int"   name="signed$__int16"    format="signed"   len="2" type_name="signed __int16"/>
	<data type="int"   name="signed$__int32"    format="signed"   len="4" type_name="signed __int32"/>
	<data type="int"   name="signed$__int64"    format="signed"   len="8" type_name="signed __int64"/>
	<data type="int"   name="unsigned$__int8"   format="unsigned" len="1" type_name="unsigned __int8"/>
	<data type="int"   name="unsigned$__int16"  format="unsigned" len="2" type_name="unsigned __int16"/>
	<data type="int"   name="unsigned$__int32"  format="unsigned" len="4" type_name="unsigned __int32"/>
	<data type="int"   name="unsigned$__int64"  format="unsigned" len="8" type_name="unsigned __int64"/>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_RS.XML
<?xml version="1.0" ?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="RS file">
  <for name="record">
    <struct>
      <data name="RS" type="string" len="2" domain='this=="RS"'/>
      <data name="length" type="int" format="u" len="4"/>
      <data name="flags"  type="int" format="u" len="1"/>
      <data name="cont"   type="int" format="u" len="1"/>
      <data name="spare"  type="none" len="6"/>
      <data name="data"   type="none" len="length"/>
      <data name="RStail" type="int" format="u" len="4" domain="this==length"/>
    </struct>
  </for>
</binary_file_format>
