=== AndrewWPhillips/HexEdit/HexEdit/TestData/BinaryFileFormat.dtd
<!ELEMENT binary_file_format ((define_struct)*, (struct|use_struct|for|if|switch|jump|eval|data)*) >
<!ELEMENT define_struct (struct|use_struct|for|if|switch|jump|eval|data)* >
<!ELEMENT struct (struct|use_struct|for|if|switch|jump|eval|data)* >
<!ELEMENT use_struct EMPTY>
<!ELEMENT for (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT if ((struct|use_struct|for|if|switch|jump|data), (else, (struct|use_struct|for|if|switch|jump|data))? ) >
<!ELEMENT else EMPTY>
<!ELEMENT switch (case)* >
<!ELEMENT case (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT jump (struct|use_struct|for|if|switch|jump|data) >
<!ELEMENT eval EMPTY>
<!ELEMENT data EMPTY>
<!ATTLIST binary_file_format name CDATA #IMPLIED
              web_site CDATA #IMPLIED
              default_byte_order (big|little) "little"
              default_read_only (false|true) "false"
              default_char_set (ascii|ansi|oem|ebcdic) "ansi"
              expr CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST define_struct
              expr CDATA #IMPLIED
              type_name CDATA #REQUIRED
              pack CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST struct name CDATA #IMPLIED
              expr CDATA #IMPLIED
              type_name CDATA #IMPLIED
              pack CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST use_struct name CDATA #IMPLIED
              expr CDATA #IMPLIED
              type_name CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST for name CDATA #IMPLIED
              count CDATA #IMPLIED
              stop_test CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>
<!ATTLIST if
              test CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST switch
              test CDATA #REQUIRED
              comment CDATA #IMPLIED>
<!ATTLIST case
              range CDATA #REQUIRED>
<!ATTLIST jump
              offset CDATA #REQUIRED
              origin (start|current|end) "current"
              comment CDATA #IMPLIED>
<!ATTLIST eval
              expr CDATA #REQUIRED
              display_error (false|true) "false"
              display_result (false|true) "false"
              comment CDATA #IMPLIED>
<!ATTLIST data name CDATA #IMPLIED
              type CDATA #REQUIRED
              format CDATA #IMPLIED
              len CDATA #IMPLIED
              bits CDATA #IMPLIED
              direction (up|down) "up"
              straddle (false|true) "false"
              byte_order (default|big|little) "default"
              read_only (default|false|true) "default"
              domain CDATA #IMPLIED
              hide CDATA #IMPLIED
              display CDATA #IMPLIED
              units CDATA #IMPLIED
              type_name CDATA #IMPLIED
              comment CDATA #IMPLIED>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_GIF.XML
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">

<binary_file_format name="GIF"
default_byte_order="little" default_read_only="false" default_char_set="ascii"
web_site="http://www.dcs.ed.ac.uk/home/mxr/gfx/2d/GIF89a.txt">
<struct name="Header" type_name="" comment="">
  <data type="string" name="Signature" format="ascii" len="3" comment="Should be
GIF"/>
  <data type="string" name="Version" format="ascii" len="3" comment="Should be
either 87a or 89a"/>
</struct>
<struct name="Logical_Screen_Descriptor" type_name="" comment="">
  <data type="int" format="unsigned" name="Logical Screen Width" len ="2"/>
  <data type="int" format="unsigned" name="Logical Screen Height" len ="2"/>
  <data type="int" format="unsigned" name="Packed_Fields" len ="1" display="bin"
comment="MSB = Global Color Table Flag(1bit) Color Resolution(3bits) Sort
Flag(1bit) Size of Global Color Table (3bits)"/>
  <data type="int" format="unsigned" name="Background Color Index" len ="1"/>
  <data type="int" format="unsigned" name="Pixel Aspect Ratio" len ="1"/>
</struct>
  <if test="Logical_Screen_Descriptor.Packed_Fields > 0x7f">
    <for name="Global Color Table" count="1 &lt;&lt;
((Logical_Screen_Descriptor.Packed_Fields &amp; 0x07)+1)" type_name="">
     <struct name="Color" type_name="" comment="">
       <data type="int" format="unsigned" name="Red" len ="1"/>
       <data type="int" format="unsigned" name="Green" len ="1"/>
       <data type="int" format="unsigned" name="Blue" len ="1"/>
     </struct>
   </for>
</if>


<for name="Field" stop_test="this.Seperator == 0x3B" type_name=""
comment="Determine the type of Field">
  <struct name="Field">
  <data type="int" format="unsigned" name="Seperator" display="hex" len ="1"
comment=""/>
  <if test="Seperator == 0x2c" comment="">
    <struct name="Image_Descriptor" type_name="" comment="Image field">
      <data type="int" format="unsigned" name="Image Left Position" len ="2"/>
      <data type="int" format="unsigned" name="Image Top Position" len ="2"/>
      <data type="int" format="unsigned" name="Image Width" len ="2"/>
      <data type="int" format="unsigned" name="Image Heigth" len ="2"/>
      <data type="int" format="unsigned" name="Packed_Fields" display="bin" len
="1"/>
      <if test="Packed_Fields > 0x7f" comment="">
        <struct name="Local Color Table" type_name="" comment="">
          <for name="Color" count="1 &lt;&lt; ((Packed_Fields &amp; 0x07)+1)"
type_name="" comment="" >
            <struct name="Color">
              <data type="int" format="unsigned" name="Red" len ="1"/>
              <data type="int" format="unsigned" name="Green" len ="1"/>
              <data type="int" format="unsigned" name="Blue" len ="1"/>
            </struct>
          </for>
        </struct>
      </if>
      <struct name="Table Based Image Data" type_name="" comment="">
        <data type="int" format="unsigned" name="LZW Minimum Code Size" len
="1"/>
        <for name="LZW Data" stop_test="this.blocksize == 0x00" type_name=""
comment="" >  
          <struct name="Data ssubblock" type_name="" comment="">
            <data type="int" format="unsigned" name="blocksize" len="1"/>
            <for count="blocksize">
            <data type="int" format="unsigned" name="data" display="hex"
len="1"/>
	      </for>
          </struct>
        </for>
      </struct>
    </struct>
  </if>
  <if test="Seperator == 0x21" comment="">
    <struct name="Extension">
    <data type="int" format="unsigned" name="Label" display="hex" len ="1"/>
    <if test="Label == 0xF9" comment="">
      <for name="Graphic Control" stop_test="this.BlockSize == 0x00"
type_name="" comment="" >
        <struct name="BLOCK" >
        <data type="int" format="unsigned" name="BlockSize" len ="1"/>
        <if test="BlockSize &gt; 0" comment="" >
          <struct name="DATA" >
          <data type="int" format="unsigned" name="Packed_Fields" len ="1"/>
          <data type="int" format="unsigned" name="Delay Time" len ="2"/>
          <data type="int" format="unsigned" name="Transparent Color Index" len
="1"/>
          </struct>
        </if>
        </struct>
      </for>
    </if>
    <if test="Label == 0xFE" comment="">
      <for name="Comment string" stop_test="this.BlockSize == 0x00" type_name=""
comment="" >
        <struct name="Comment string">
        <data type="int" format="unsigned" name="BlockSize" len ="1"/>
        <if test="BlockSize &gt; 0x00" >
          <data type="string" format="ascii" name="data" len ="BlockSize"/>
        </if>
        </struct>
      </for>
    </if>
    <if test="Label == 0x01" comment="">
        <struct name="Plain text" >
          <data type="int" format="unsigned" name="BlockSize" len ="1"/>
          <data type="int" format="unsigned" name="Text Grid Left Posistion" len
="2"/>
          <data type="int" format="unsigned" name="Text Grid Top Posistion" len
="2"/>
          <data type="int" format="unsigned" name="Text Grid Width" len ="2"/>
          <data type="int" format="unsigned" name="Text Grid Height" len ="2"/>
          <data type="int" format="unsigned" name="Character Cell Width" len
="1"/>
          <data type="int" format="unsigned" name="Character Cell Height" len
="1"/>
          <data type="int" format="unsigned" name="Text Foreground Color Index"
len ="1"/>
          <data type="int" format="unsigned" name="Text Background Color Index"
len ="1"/>
          <for name="text" stop_test="this.blocksize == 0x00" type_name=""
comment="" >  
            <struct name="Data subblock" type_name="" comment="">
              <data type="int" format="unsigned" name="blocksize" len ="1"/>
              <data type="string" format="ascii" name="data" len ="blocksize"/>	
            </struct>
          </for>
        </struct>
    </if>

    <if test="Label == 0xFF">
      <struct name="Application">
        <data type="int" format="unsigned" name="BlockSize" len ="1"
comment="Should always be 11"/>   
        <data type="string" format="ascii" name="Application Identifier" len
="8"/>
        <data type="string" format="ascii" name="Application Authentication
Code" len ="3"/>
        <for name="Data" stop_test="this.blocksize == 0x00" type_name=""
comment="" >  
          <struct name="Application Data" type_name="" comment="">
            <data type="int" format="unsigned" name="blocksize" len ="1"/>
            <data type="none" display="hex" name="data" len ="blocksize"/>	
          </struct>
        </for>       
     </struct>
    </if>

   </struct>
  </if>
</struct>
</for>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_MPG.xml
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="MPEG" type_name="" comment="" expr="">
	<define_struct type_name="header" comment="" expr="={this.start_code;%.02X}">
		<data type="int" name="start_code" format="unsigned" domain="this &gt;= 0x00000100 &amp;&amp; this &lt;= 0x000001FF" display="" byte_order="big" len="4"/>
		<if test="start_code==0x000001BA" comment="">
			<struct name="PackLayer" type_name="" comment="" expr="">
				<data type="none" name="PackLayerData" len="8"/>
			</struct>
		</if>
		<if test="start_code==0x000001BB" comment="">
			<struct name="SystemHeader" type_name="" comment="" expr="">
				<data type="int" name="header_length" format="unsigned" len="2" display="" byte_order="big"/>
				<data type="none" name="SystemHeaderData" len="header_length"/>
			</struct>
		</if>
		<if test="start_code==0x000001BE" comment="">
			<struct name="Padding Stream" type_name="" comment="" expr="">
				<data name="padding_length" type="int" len="2" format="unsigned" display="" byte_order="big"/>
				<data type="none" name="padding" len="padding_length"/>
			</struct>
		</if>
		<if test="start_code==0x000001E0" comment="">
			<struct name="Video Packet Stream" type_name="" comment="" expr="">
				<data name="packet_length" type="int" len="2" format="unsigned" display="" byte_order="big"/>
				<data type="none" name="VideoPacketStreamData" len="packet_length"/>
			</struct>
		</if>
		<if test="start_code==0x000001C0" comment="">
			<struct name="Audio Packet Stream" type_name="" comment="" expr="">
				<data name="packet_length" type="int" len="2" format="unsigned" display="" byte_order="big"/>
				<data type="none" name="AudioPacketStreamData" len="packet_length"/>
			</struct>
		</if>
	</define_struct>
	<for name="header" count="99" stop_test="" type_name="" comment="">
		<use_struct name="head" expr="" type_name="header" comment=""/></for>
	<data type="none" name="unparsed_data"/></binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_HEG.xml
<?xml version="1.0" ?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="HEG_File" type_name="" comment="">
	<define_struct type_name="square" comment="" expr="({this.dx} X {this.dy})  at ({this.x}, {this.y})">
		<data type="int" name="flags" format="unsigned" len="1" display="hex" domain="this == 0" />
		<data type="int" name="colid" format="unsigned" len="2" />
		<data type="real" name="x" format="ieee" len="4" />
		<data type="real" name="y" format="ieee" len="4" />
		<data type="real" name="dx" format="ieee" len="4" domain="this &gt; 0.0" />
		<data type="real" name="dy" format="ieee" len="4" domain="this &gt; 0.0" />
	</define_struct>
	<define_struct type_name="circle" comment="" expr="radius=this.radius at ({this.x}, {this.y})">
		<data type="int" name="flags" format="unsigned" len="1" display="hex" domain="this == 0" />
		<data type="int" name="colid" format="unsigned" len="2" />
		<data type="real" name="x" format="ieee" len="4" />
		<data type="real" name="y" format="ieee" len="4" />
		<data type="real" name="radius" format="ieee" len="4" domain="this &gt; 0.0" />
	</define_struct>
	<define_struct type_name="group" comment="" expr="{this.count} sub-objects">
		<data type="int" name="flags" format="unsigned" len="1" display="hex" domain="this == 0" />
		<data type="int" name="count" format="unsigned" len="2" comment="Number of grouped objects." />
		<data type="real" name="x" format="ieee" len="4" />
		<data type="real" name="y" format="ieee" len="4" />
		<for name="object" count="count" stop_test="" type_name="" comment="">
			<struct name="" type_name="" comment="">
				<data type="int" name="next_type" format="signed" len="1" />
				<if test="next_type == 1" comment="">
					<use_struct name="sub_square" type_name="square" comment="" />
				</if>
				<if test="next_type == 2" comment="">
					<use_struct name="sub_circle" type_name="circle" comment="" />
				</if>
				<if test="next_type == 10" comment="">
					<use_struct name="sub_group" type_name="group" comment="" />
				</if>
			</struct>
		</for>
	</define_struct>
	<struct name="header" type_name="" comment="">
		<data type="int" name="magic" format="unsigned" len="4" domain="this == 0x16071958" display="hex"
			comment="HEG file magic number - should always be 16071958 hex." />
		<data type="date" name="created" format="c" comment="When the image was created." />
		<data type="date" name="modified" format="c" comment="When the image was last changed."
			domain="this &gt; created" />
		<data type="int" name="colour_table_address" format="unsigned" len="4" display="hex" comment="Address in the file of the colours table." />
	</struct>
	<for name="object" count="" stop_test="this.next_type == 0" type_name="" comment="">
		<struct name="" type_name="" comment="" expr="{this.next_type == 1 ? &quot;SQUARE&quot; : (this.next_type == 2 ? &quot;CIRCLE&quot; : (this.next_type == 10 ? &quot;GROUP&quot; : &quot;END&quot;))}">
			<data type="int" name="next_type" format="unsigned" len="1" />
			<if test="next_type == 1" comment="">
				<use_struct name="square" type_name="square" comment="" />
			</if>
			<if test="next_type == 2" comment="">
				<use_struct name="circle" type_name="circle" comment="" />
			</if>
			<if test="next_type == 10" comment="">
				<use_struct name="group" type_name="group" comment="" />
			</if>
		</struct>
	</for>
	<data type="none" name="dummy" len="1" comment="Extra byte for word alignment." />
	<data type="int" name="num_cols" format="unsigned" len="2" domain="this &gt; 0" />
	<for name="col" count="num_cols" stop_test="" type_name="" comment="">
		<struct name="" type_name="" comment="">
			<data type="string" name="name" format="ascii" len="13" />
			<data type="int" name="red" format="unsigned" len="1" />
			<data type="int" name="green" format="unsigned" len="1" />
			<data type="int" name="blue" format="unsigned" len="1" />
		</struct>
	</for>
</binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_SWF.XML
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="SWF_Macromedia_Flash_File_Format" web_site="http://www.openswf.org/spec.html" type_name="" comment="Macromedia Flash File Format (SWF)" default_byte_order="little" default_read_only="true" default_char_set="ansi">
	<struct name="hdr" type_name="SWF File Header" comment="All SWF files begin with this header"><data type="string" name="Signature" format="ascii" len="3" domain="this == &quot;FWS&quot;" display="" comment="Magic characters that identify a .SWF file."/><data type="int" name="Version" format="unsigned" len="1" read_only="false" display="" comment="File version $04 fro SWF 4"/><data type="int" name="FileLength" format="unsigned" len="4" display="" comment="Length of entire file in bytes" units="bytes"/><struct name="FrameSize" type_name="RECT" comment="Frame size in TWIPS"><data type="int" name="NBits_5" format="unsigned" len="1" display="" comment="High five bites is number of bits of each of next 4 fields (Xmin, Xmax, Ymin, Ymax)"/><data type="none" name="REST" len="((NBits_5&gt;&gt;3)*4+5-1)/8" comment="This and lower 3 bits of previous byte encodes the 4 coords of the RECT"/></struct><data type="int" name="FrameRate1" format="unsigned" len="1" display="" units="frame/sec" comment="Frame delay (seconds part)"/><data type="int" name="FrameRate2" format="unsigned" len="1" display="" comment="Frame rate (fraction part)"/><data type="int" name="FrameCount" format="unsigned" len="2" display="" comment="Total number of frames in movie"/></struct><for name="tag" count="" stop_test="" type_name="" comment=""><struct name="" type_name="" comment=""><data type="int" name="Code" format="unsigned" len="2" display="" comment="Top 10 bits is the tag for the record type.  Bottom 6 bits is the tag length.  If bottom 6 bits is 63 (all bits on) then the real length is in following DWORD."/><if test="(Code &amp; 0x3F) &lt; 0x3F" comment="Short tag (length less than 63)"><data type="none" name="TagData_short" len="Code &amp; 0x3F" comment="The data for the short tag"/></if><if test="(Code &amp; 0x3F) == 0x3F" comment="Long tag (length &gt;= 63)"><struct name="LongTag" type_name="" comment="Length of long tag folllowed by the data"><data type="int" name="Length" format="unsigned" len="4" display="" comment="Length of long tag if short tag length is $3F"/><data type="none" name="TagData" len="Length" comment="Long tag data"/></struct></if></struct></for></binary_file_format>

=== AndrewWPhillips/HexEdit/HexEdit/TestData/_png.xml
<?xml version="1.0"?>
<!DOCTYPE binary_file_format SYSTEM "BinaryFileFormat.dtd">
<binary_file_format name="PNG" allow_editing="false" default_byte_order="big" comment="Portable Network Graphic (PNG) file format, with support for animated PNGs!" default_char_set="ansi" web_site="http://www.fileformat.info/format/png/corion.htm">
    <define_struct type_name="CHUNK">
        <data name="length" type="int" format="unsigned" len="4" display=""/>
        <data name="type" type="string" format="ascii" len="4" display=""/>
        <switch test="type">
            <case range="IHDR">
                <struct name="header" comment="Image header">
                    <data name="width" type="int" format="signed" len="4" domain="this &gt; 0" comment="Image width in pixels. Zero is an invalid value. The maximum for each is (2^31)-1 in order to accommodate languages which have difficulty with unsigned 4-byte values."/>
                    <data name="height" type="int" format="signed" len="4" domain="this &gt; 0" comment="Image height in pixels. Zero is an invalid value. The maximum for each is (2^31)-1 in order to accommodate languages which have difficulty with unsigned 4-byte values."/>
                    <data name="bitDepth" type="int" format="unsigned" len="1" comment="Number of bits per pixel (for palette images) or per sample (for grayscale and truecolor images)"/>
                    <data name="colourType" type="int" format="unsigned" len="1" comment=""/>
                    <data name="compressionType" type="int" format="unsigned" len="1" comment=""/>
                    <data name="filterType" type="int" format="unsigned" len="1" domain="{ADAPTIVE=0}" comment=""/>
                    <data name="interlaceType" type="int" format="unsigned" len="1" domain="{NONE=0,ADAM7=1}" comment=""/>
                </struct>
            </case>
            <case range="PLTE">
                <struct name="palette">
                    <for name="colour" count="length/3">
                        <data name="rgb" type="none" len="3"/>
                    </for>
                </struct>
            </case>
            <case range="IDAT">
                <data name="imageData" type="none" len="length"/>
            </case>
            <case range="IEND">
                <data name="end" type="none" len="0"/>
            </case>
            <case range="bKGD">
                <data name="backgroundColour" type="none" len="length"/>
            </case>
            <case range="cHRM">
                <struct name="primaryChromaticities" comment="Applications that need precise specification of colors in a PNG file may use this chunk to specify the chromaticities of the red, green, and blue primaries used in the image, and the referenced white point">
                    <data name="whitePointX" type="int" format="unsigned" len="4"/>
                    <data name="whitePointY" type="int" format="unsigned" len="4"/>
                    <data name="redX" type="int" format="unsigned" len="4"/>
                    <data name="redY" type="int" format="unsigned" len="4"/>
                    <data name="greenX" type="int" format="unsigned" len="4"/>
                    <data name="greenY" type="int" format="unsigned" len="4"/>
                    <data name="blueX" type="int" format="unsigned" len="4"/>
                    <data name="blueY" type="int" format="unsigned" len="4"/>
                </struct>
            </case>
            <case range="gAMA">
                <data name="gammaCorrection" type="none" len="length" comment="Divide by 100000.0 to get real value"/>
            </case>
            <case range="hIST">
                <data name="imageHistogram" type="none" len="length" comment="Gives the approximate usage frequency of each color in the color palette. A histogram chunk may appear only when a palette chunk appears"/>
            </case>
            <case range="pHYs">
                <struct name="physicalDimensions" comment="Specifies the intended resolution for display of the image">
                    <data name="pixelsPerUnitX" type="int" format="unsigned" len="4"/>
                    <data name="pixelsPerUnitY" type="int" format="unsigned" len="4"/>
                    <data name="units" type="int" format="unsigned" len="1" domain="{UNKNOWN=0,METERS=1}"/>
                </struct>
            </case>
            <case range="sBIT">
                <data name="significantBits" type="none" len="length"/>
            </case>
            <case range="tEXt">
                <struct name="textData" comment="Contains any textual information">
                    <eval expr="startAddr = addressof(this)"/>
                    <data name="keyword" type="string" comment="Null-terminated string containing the type of text information"/>
                    <data name="text" type="string" len="length - (addressof(this) - startAddr)" comment="The actual text information"/>
                </struct>
            </case>
            <case range="tIME">
                <struct name="lastModificationTime">
                    <data name="year" type="int" format="unsigned" len="2" comment="Full 4-digit year"/>
                    <data name="month" type="int" format="unsigned" len="1"/>
                    <data name="day" type="int" format="unsigned" len="1"/>
                    <data name="hour" type="int" format="unsigned" len="1"/>
                    <data name="minute" type="int" format="unsigned" len="1"/>
                    <data name="second" type="int" format="unsigned" len="1"/>
                </struct>
            </case>
            <case range="tRNS">
                <data name="transparencyData" type="none" len="length" comment="Transparency data for each entry in the palette. Used as an alternative to an alpha channel"/>
            </case>
            <case range="zTXt">
                <struct name="compressedTextData" comment="Contains any textual information in compressed form">
                    <eval expr="startAddr = addressof(this)"/>
                    <data name="keyword" type="string" comment="Null-terminated string containing the type of text information"/>
                    <data name="compressionType" type="int" format="unsigned" len="1"/>
                    <data name="data" type="none" len="length - (addressof(this) - startAddr)" comment="The compressed text information"/>
                </struct>
            </case>
            <case range="acTL">
                <struct name="animationControl" comment="Control data for animated PNGs">
                    <data name="numFrames" type="int" format="unsigned" len="4" comment="Number of frames"/>
                    <data name="numPlays" type="int" format="unsigned" len="4" comment="Number of times to loop, 0 indicates infinite looping"/>
                </struct>
            </case>
            <case range="fcTL">
                <struct name="frameControl" comment="">
                    <data name="sequenceNumber" type="int" format="unsigned" len="4" comment="Sequence number of the animation chunk, starting from 0"/>
                    <data name="width" type="int" format="unsigned" len="4"/>
                    <data name="height" type="int" format="unsigned" len="4"/>
                    <data name="xOffset" type="int" format="unsigned" len="4" comment="X position at which to render the following frame"/>
                    <data name="yOffset" type="int" format="unsigned" len="4" comment="Y position at which to render the following frame"/>
                    <data name="delayNumerator" type="int" format="unsigned" len="2"/>
                    <data name="delayDenominator" type="int" format="unsigned" len="2"/>
                    <data name="disposeOp" type="int" format="unsigned" len="1" domain="{NONE,BACKGROUND,PREVIOUS}" comment="Type of frame area disposal to be done after rendering this frame"/>
                    <data name="blendOp" type="int" format="unsigned" len="1" domain="{SOURCE,OVER}" comment="Type of frame area rendering for this frame"/>
                </struct>
            </case>
            <case range="fdAT">
                <struct name="frameData" comment="">
                    <data name="sequenceNumber" type="int" format="unsigned" len="4" comment="Sequence number of the animation chunk, starting from 0"/>
                    <data name="frameData" type="none" len="length-4"/>
                </struct>
            </case>
            <case range="">
                <data name="unknownData" type="none" len="length"/>
            </case>
        </switch>
        <data name="CRC" type="none" len="4" display=""/>
    </define_struct>
    <data name="signature" type="none" len="8"/>
    <for name="chunk" count="" stop_test="">
        <use_struct name="chunk" type_name="CHUNK"/>
    </for>
</binary_file_format>
